name: Linux riscv64

on:
  push:
    branches: [test/riscv64]
  workflow_dispatch:
    inputs:
      sdk:
        description: "URL of the dotnet sdk"
        required: false
      nupkg:
        description: "URL of the dotnet nupkg"
        required: false

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu22.04
          install: |
            apt-get update && apt-get install -y curl git libicu-dev
            #add-apt-repository ppa:ubuntu-toolchain-r/test
            #apt-get update && apt-get install --only-upgrade -y libstdc++6 --no-install-recommends
            #apt-get upgrade -y
          run: |
            echo "Downloading SDK"
            curl -sL ${{ github.event.inputs.sdk || 'https://b7lwda.db.files.1drv.com/y4mCsjXlVAT4KBvULhkuz0uAjyqcIXk37_GuLHd3J8D7dq1lLM6_lI7uUW1o5v3vkCsJmADqXtWPLWGBY_-eF5iKJRRhWEc_lubEuzoYefRQA-jZxcV_1Sw6RUUo4lbcWgF-o8Uvc3yhEy7yI9pDQbExmm8AZ3xLV5mOky_o_v6EFqy2PwA-q4tVW3tqpZyLwN8uaMEzQ3oM11tTciUEgCIacoTdjH4__lSAHav0JsnfTA?AVOverride=1' }} -o dotnet.tar.gz
            #echo "Downloading NuGet packages"
            #curl -sL ${{ github.event.inputs.nupkg || 'https://cllqda.db.files.1drv.com/y4mqSe4TK8P-7oojLaiJFBECMThnmwaD94nFltbbD5H6s5TSKeE5MpxnsGwtHcTlG3yRv3vlXCqGJ4j_2RvRWFRWBNd0hbB74w9ljS3bGNkuVJaOY6mA1anezvbYIGskJ9PlW_xsTs0ZGzkPgWC1SSa6jk0_q5LAHUdCjMmo-nFNZ4hkiAp4hdFusGsqnKptzTxOf8lY7Fk38wM-BdsfilODTjw1t7dzn2graFDRFA4FGg?AVOverride=1' }} -o nupkg.tar
            #mkdir -p nupkg
            #tar -xf nupkg.tar -C nupkg
            mkdir -p sdk
            tar -xf dotnet.tar.gz -C sdk
            cd sdk
            echo "Creating a new app"
            ./dotnet --version
            ./dotnet --version
            ./dotnet new console -n MyConsoleApp
            #mv ../nuget.config ./MyConsoleApp/nuget.config
            echo 'Console.WriteLine("🎄 Merry Christmas from .NET on riscv64 🎅");' >> ./MyConsoleApp/Program.cs
            echo "Building the app"
            #./dotnet publish ./MyConsoleApp/MyConsoleApp.csproj -c release -r linux-riscv64 -o ./MyConsoleApp/pub --sc true -p:PublishSingleFile=true
            ls ./MyConsoleApp/pub
            ./dotnet build ./MyConsoleApp/MyConsoleApp.csproj
            echo "Running test app..."
            ./MyConsoleApp/pub/MyConsoleApp
            #./dotnet ./MyConsoleApp/bin/Debug/net8.0/MyConsoleApp.dll
            uname -a
