name: Linux riscv64

on:
  push:
    branches: [test/linux-riscv64]
  workflow_dispatch:
    inputs:
      url:
        description: "URL of the dotnet sdk"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu22.04
          install: |
            apt-get update && apt-get install -y curl libicu-dev
          run: |
            curl -sL ${{ github.event.inputs.url || 'https://dlilrw.db.files.1drv.com/y4md2A1sJXbE1KFmCvnb__7FavGjdnslz2a732EmzUPSXzJ4wNbH8i6TCClHmFcTHSXnhsMMYe7mphiaKQoMj9nqgBjEvT2TgtpaGmZ1UiFbGJW8pBjzwI9MMUzKR1ygUesfjQgLhwEkkF_VkccRi9qZn6RE6eMzDHsHhz8Cb6RUxncqX0kwbeu0Ugg9HFy0Y4ly94k9FVBuRrw2LLG014e-OuW6satwfCwY7d8getC2Ac?AVOverride=1' }} -o dotnet.tar.gz
            mkdir -p sdk
            tar -xf dotnet.tar.gz -C sdk
            cd sdk
            echo "aaa"
            ./dotnet new console -n MyConsoleApp
            ls ./MyConsoleApp
            ./dotnet build ./MyConsoleApp/MyConsoleApp.csproj
            ./dotnet ./MyConsoleApp/bin/Debug/net8.0/MyConsoleApp.dll
            #echo "bbb"
            sleep 40s
