name: Linux riscv64

on:
  push:
    branches: [test/linux-riscv64]
  workflow_dispatch:
    inputs:
      url:
        description: "URL of the dotnet sdk"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu22.04
          install: |
            apt-get update && apt-get install -y curl libicu-dev
          run: |
            curl -sL ${{ github.event.inputs.url || 'https://dlilrw.db.files.1drv.com/y4mdKCtNZrh509o2rAOm5v_E6JQ3c50lDosodJ1HrbiqNN24dnL2FEL2JkmBRStMHuw0J8ztXx3JXjOzZYuk8ebf-mEHJGeb54PF1hD3W_hYxzgGKWolZZ1-QGQgn-Pb52T5QZaqHwkR0nYtM0gtQo1I83LzNE4Kw_yCxUEHETJsUDaEWdzlgBqPC3HEQrkP_qYzOcRnpMvvjuI0o98_5C6MA' }} -o dotnet.tar.gz
            mkdir -p sdk
            tar -xf dotnet.tar.gz -C sdk
            cd sdk
            echo "aaa"
            ./dotnet new console -n MyConsoleApp
            #ls ./MyConsoleApp
            echo 'Console.WriteLine("🎄 Merry Christmas from .NET on riscv64 🎅");' >> ./MyConsoleApp/Program.cs
            ./dotnet build ./MyConsoleApp/MyConsoleApp.csproj
            ./dotnet ./MyConsoleApp/bin/Debug/net8.0/MyConsoleApp.dll
            #echo "bbb"
            #sleep 40s
